import React from "react";
import { render, screen } from "@testing-library/react";
import "@testing-library/jest-dom";
import MarkdownBriefing from "./MarkdownBriefing";

describe("MarkdownBriefing", () => {
  it("renders plain paragraph text", () => {
    render(<MarkdownBriefing content="Hello world" />);
    expect(screen.getByText("Hello world")).toBeInTheDocument();
  });

  it("renders an h1 heading", () => {
    render(<MarkdownBriefing content="# Morning Briefing" />);
    expect(screen.getByRole("heading", { level: 1, name: "Morning Briefing" })).toBeInTheDocument();
  });

  it("renders an h2 heading", () => {
    render(<MarkdownBriefing content="## Critical Exceptions" />);
    expect(screen.getByRole("heading", { level: 2, name: /Critical Exceptions/ })).toBeInTheDocument();
  });

  it("renders bold text as strong", () => {
    const { container } = render(<MarkdownBriefing content="**CRITICAL** item" />);
    expect(container.querySelector("strong")).toHaveTextContent("CRITICAL");
  });

  it("renders a GFM table with headers and cells", () => {
    const content = `
| Priority | Count |
|---|---|
| CRITICAL | 3 |
| HIGH | 7 |
`;
    render(<MarkdownBriefing content={content} />);
    expect(screen.getByRole("table")).toBeInTheDocument();
    expect(screen.getByText("Priority")).toBeInTheDocument();
    expect(screen.getByText("Count")).toBeInTheDocument();
    expect(screen.getByText("CRITICAL")).toBeInTheDocument();
    expect(screen.getByText("3")).toBeInTheDocument();
  });

  it("renders a blockquote", () => {
    const { container } = render(<MarkdownBriefing content="> Executive summary goes here" />);
    expect(container.querySelector("blockquote")).toBeInTheDocument();
    expect(screen.getByText("Executive summary goes here")).toBeInTheDocument();
  });

  it("renders an unordered list", () => {
    const content = "- Item one\n- Item two\n- Item three";
    render(<MarkdownBriefing content={content} />);
    expect(screen.getByText("Item one")).toBeInTheDocument();
    expect(screen.getByText("Item two")).toBeInTheDocument();
    expect(screen.getByText("Item three")).toBeInTheDocument();
  });

  it("renders inline code", () => {
    const { container } = render(<MarkdownBriefing content="Use `VND-400` for vendor lookup" />);
    expect(container.querySelector("code")).toHaveTextContent("VND-400");
  });

  it("renders a horizontal rule", () => {
    const { container } = render(<MarkdownBriefing content={"Before\n\n---\n\nAfter"} />);
    expect(container.querySelector("hr")).toBeInTheDocument();
  });

  it("renders a link with target=_blank", () => {
    render(<MarkdownBriefing content="[Dashboard](http://localhost:3000)" />);
    const link = screen.getByRole("link", { name: "Dashboard" });
    expect(link).toHaveAttribute("href", "http://localhost:3000");
    expect(link).toHaveAttribute("target", "_blank");
    expect(link).toHaveAttribute("rel", "noopener noreferrer");
  });

  it("renders a realistic briefing section without crashing", () => {
    const briefing = `
# 📋 Morning Briefing — 2026-04-21

> **3 CRITICAL exceptions** require immediate attention. Estimated $42,000 at risk.

## 🚨 Critical Exceptions

| Exception | Store | Est. Lost Sales |
|---|---|---|
| OOS – Organic Oat Milk | STR-001 (Tier 1, LA) | $28,000 |
| OOS – Premium Coffee | STR-003 (Tier 1, NYC) | $14,000 |

## ⚠️ Vendor Pattern Alert

**VND-400 (CleanHome Distributors)** showing systemic deterioration:
- 14 exceptions across 8 stores
- Fill rate: 72% (below 85% threshold)
- Recommend escalation to supply chain manager

---

*Generated by Exception Copilot AI*
`;
    render(<MarkdownBriefing content={briefing} />);
    expect(screen.getByRole("heading", { level: 1 })).toBeInTheDocument();
    expect(screen.getByRole("table")).toBeInTheDocument();
    expect(screen.getByText(/VND-400/)).toBeInTheDocument();
  });
});
